### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by emaks**

### CODE REVIEW

**Comment by lanwen** [comment]
something goes wrong

**Comment by emaks** [comment]
fixed

**Comment by emaks** [comment]
@lanwen Could you make maven release with this changes?

**Comment by lanwen** [comment]
@emaks Released far ago as 1.4

**Comment by lanwen** [comment]
@emaks hmm, sorry, something strange - don't see in central

**Comment by lanwen** [comment]
@emaks reuploaded as `1.4.1` (should be available shortly), sorry for inconvenience, thanks for paying attention

**Pull request merged**
